policy_file: "rl_stamp_tracking/policies/policy.mnn"
time_step_total: 119

joint_names:
  [
    "J00_HIP_PITCH_L",
    "J06_HIP_PITCH_R",
    "J12_WAIST_YAW",
    "J01_HIP_ROLL_L",
    "J07_HIP_ROLL_R",
    "J13_SHOULDER_PITCH_L",
    "J18_SHOULDER_PITCH_R",
    "J23_HEAD_YAW",
    "J02_HIP_YAW_L",
    "J08_HIP_YAW_R",
    "J14_SHOULDER_ROLL_L",
    "J19_SHOULDER_ROLL_R",
    "J03_KNEE_PITCH_L",
    "J09_KNEE_PITCH_R",
    "J15_SHOULDER_YAW_L",
    "J20_SHOULDER_YAW_R",
    "J04_ANKLE_PITCH_L",
    "J10_ANKLE_PITCH_R",
    "J16_ELBOW_PITCH_L",
    "J21_ELBOW_PITCH_R",
    "J05_ANKLE_ROLL_L",
    "J11_ANKLE_ROLL_R",
    "J17_ELBOW_YAW_L",
    "J22_ELBOW_YAW_R",
  ]

joint_stiffness:
  [
    104.924,
    110.401,
    42.660,
    106.661,
    100.879,
    43.385,
    40.919,
    45.962,
    51.720,
    41.515,
    57.254,
    59.072,
    136.755,
    110.785,
    57.720,
    47.023,
    47.076,
    50.027,
    42.399,
    43.971,
    43.383,
    54.190,
    47.202,
    47.751,
  ]

joint_damping:
  [
    11.931,
    8.043,
    5.002,
    8.326,
    10.577,
    4.618,
    4.830,
    5.858,
    4.916,
    5.201,
    5.919,
    5.008,
    8.382,
    11.226,
    4.344,
    5.352,
    4.443,
    5.584,
    4.339,
    5.984,
    4.609,
    5.603,
    4.434,
    5.180,
  ]

default_joint_pos:
  [
    -0.066,
    -0.054,
    -0.006,
    -0.006,
    0.009,
    -0.006,
    -0.003,
    -0.001,
    -0.003,
    -0.003,
    0.158,
    -0.153,
    0.122,
    0.111,
    -0.009,
    0.002,
    -0.056,
    -0.069,
    -0.248,
    -0.245,
    0.003,
    -0.005,
    0.003,
    0.010,
  ]

action_scale:
  [
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
  ]

observation_names:
  [
    "command",
    "motion_anchor_pos_b",
    "motion_anchor_ori_b",
    "base_lin_vel",
    "base_ang_vel",
    "joint_pos",
    "joint_vel",
    "actions",
  ]
observation_history_lengths: [3, 3, 3, 3, 3, 3, 3, 3]

transition_duration_s: 0.0
loop_motion: false
reset_observation_history_on_loop: false
auto_transition: true
align_reference_to_robot_anchor: true
