policy_file: "rl_power_shot_tracking/policies/policy.mnn"
time_step_total: 172

joint_names:
  [
    "J00_HIP_PITCH_L",
    "J06_HIP_PITCH_R",
    "J12_WAIST_YAW",
    "J01_HIP_ROLL_L",
    "J07_HIP_ROLL_R",
    "J13_SHOULDER_PITCH_L",
    "J18_SHOULDER_PITCH_R",
    "J23_HEAD_YAW",
    "J02_HIP_YAW_L",
    "J08_HIP_YAW_R",
    "J14_SHOULDER_ROLL_L",
    "J19_SHOULDER_ROLL_R",
    "J03_KNEE_PITCH_L",
    "J09_KNEE_PITCH_R",
    "J15_SHOULDER_YAW_L",
    "J20_SHOULDER_YAW_R",
    "J04_ANKLE_PITCH_L",
    "J10_ANKLE_PITCH_R",
    "J16_ELBOW_PITCH_L",
    "J21_ELBOW_PITCH_R",
    "J05_ANKLE_ROLL_L",
    "J11_ANKLE_ROLL_R",
    "J17_ELBOW_YAW_L",
    "J22_ELBOW_YAW_R",
  ]

joint_stiffness:
  [
    102.472,
    137.068,
    44.987,
    123.009,
    111.444,
    59.872,
    58.185,
    47.369,
    45.854,
    52.111,
    51.753,
    43.614,
    115.479,
    122.581,
    53.013,
    58.623,
    50.903,
    59.688,
    51.907,
    41.695,
    58.449,
    52.702,
    57.460,
    43.007,
  ]

joint_damping:
  [
    9.820,
    8.794,
    4.861,
    10.110,
    11.282,
    4.431,
    5.770,
    4.260,
    5.433,
    5.271,
    5.002,
    5.231,
    11.223,
    11.460,
    4.411,
    4.582,
    4.964,
    4.797,
    5.157,
    5.400,
    4.890,
    5.431,
    5.184,
    4.088,
  ]

default_joint_pos:
  [
    -0.061,
    -0.054,
    0.008,
    0.005,
    -0.005,
    -0.004,
    -0.005,
    -0.005,
    0.006,
    0.002,
    0.149,
    -0.153,
    0.122,
    0.117,
    0.004,
    -0.003,
    -0.064,
    -0.057,
    -0.255,
    -0.248,
    -0.003,
    -0.005,
    0.008,
    0.000,
  ]

action_scale:
  [
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
    0.5,
  ]

observation_names:
  [
    "command",
    "motion_anchor_pos_b",
    "motion_anchor_ori_b",
    "base_ang_vel",
    "joint_pos",
    "joint_vel",
    "actions",
    "projected_gravity",
    "joint_error",
    "motion_phase",
  ]
observation_history_lengths: [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]

transition_duration_s: 0.0
loop_motion: false
reset_observation_history_on_loop: false
auto_transition: true
align_reference_to_robot_anchor: true
